language: "en"
early_access: false
reviews:
  high_level_summary: false
  poem: false
  review_status: false
  collapse_walkthrough: false
  path_instructions:
    - path: "**/*.mdx"
      instructions: |
        "ALWAYS review Markdown content THOROUGHLY with the following criteria:
        - Use proper nouns in place of personal pronouns like 'We' and 'Our' to maintain consistency in communal documentation.
        - Avoid gender-specific language and use the imperative form.
        - Monitor capitalization for emphasis. Avoid using all caps, italics, or bold for emphasis.
        - Ensure proper nouns are capitalized in sentences.
        - Apply the Oxford comma.
        - Use proper title case for buttons, tab names, page names, and links. Sentence case should be used for body content and short phrases, even in links.
        - Use correct spelling and grammar at all times (IMPORTANT).
        - For H1, H2, and H3 headers:
          1. Use sentence case, capitalizing only the first word.
          2. Preserve the capitalization of proper nouns, technical terms, and acronyms. Examples include 'Optimism', 'OP Mainnet', 'Ethereum', 'JavaScript', 'NFT', etc.
          3. Do not automatically lowercase words that might be proper nouns or technical terms.
        - Flag any headers that seem to inconsistently apply these rules for manual review.
        - Refer to a predefined list of proper nouns and technical terms specific to the project, which should be kept capitalized regardless of their position in the header.
        "
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
chat:
  auto_reply: true
