version: 2.1
orbs:
  node: circleci/node@7.0.0

executors:
  node20:
    docker:
      - image: cimg/node:20.11.1 # Prebuilt CircleCI image for Node.js 20.x
    resource_class: medium # Adjust resource allocation as needed
  ubuntu:
    machine:
      image: ubuntu-2204:current

jobs:
  publish-algolia-search:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install Node.js (20.x) and pnpm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install -g pnpm
            pnpm --version
      - restore_cache:
          keys:
            - v1-pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install dependencies
          command: npm install -g pnpm && pnpm install
      - save_cache:
          key: v1-pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

      - run:
          name: Create and upload index
          command: pnpm index:docs
          environment:
            ALGOLIA_APPLICATION_ID: $ALGOLIA_APPLICATION_ID
            ALGOLIA_WRITE_API_KEY: $ALGOLIA_WRITE_API_KEY
            ALGOLIA_INDEX_NAME: $ALGOLIA_INDEX_NAME

workflows:
  main:
    jobs:
      - publish-algolia-search:
          context: algolia-search
          filters:
            branches:
              only: main
