version: 2.1
orbs:
  node: circleci/node@7.0.0

jobs:
  publish-algolia-search:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Install dependencies
          command: pnpm install
      # - run:
      #     name: Create and upload index
      #     command: pnpm index:docs
      #     environment:
      #       ALGOLIA_APPLICATION_ID: $ALGOLIA_APPLICATION_ID
      #       ALGOLIA_WRITE_API_KEY: $ALGOLIA_WRITE_API_KEY
      #       ALGOLIA_INDEX_NAME: $ALGOLIA_INDEX_NAME

workflows:
  main:
    jobs:
      - publish-algolia-search:
          context: algolia-search
          filters:
            branches:
              only: main
  test:
    jobs:
      - publish-algolia-search
