version: 2.1
orbs:
  node: circleci/node@7.0.0

executors:
  node20:
    docker:
      - image: cimg/node:20.11.1 # Prebuilt CircleCI image for Node.js 20.x
    resource_class: medium # Adjust resource allocation as needed
  ubuntu:
    machine:
      image: ubuntu-2204:current

jobs:
  publish-algolia-search:
    executor: node20
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install dependencies
          command: npm install -g pnpm && pnpm install
      - save_cache:
          key: v1-pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

      # - run:
      #     name: Create and upload index
      #     command: pnpm index:docs
      #     environment:
      #       ALGOLIA_APPLICATION_ID: $ALGOLIA_APPLICATION_ID
      #       ALGOLIA_WRITE_API_KEY: $ALGOLIA_WRITE_API_KEY
      #       ALGOLIA_INDEX_NAME: $ALGOLIA_INDEX_NAME

workflows:
  main:
    jobs:
      - publish-algolia-search:
          context: algolia-search
          filters:
            branches:
              only: main
  test:
    jobs:
      - publish-algolia-search
