```yaml
name: Check Breadcrumbs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'pages/**/*.mdx'
      - 'pages/**/*.md'

jobs:
  check-breadcrumbs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Create check-breadcrumbs script
      run: |
        cat > utils/check-breadcrumbs.ts << 'EOL'
        import * as fs from 'fs/promises';
        import * as path from 'path';

        const rootDir = path.join(process.cwd(), 'pages');
        const errors: string[] = [];

        async function checkDirectory(dirPath: string): Promise<void> {
          const entries = await fs.readdir(dirPath, { withFileTypes: true });
          
          for (const entry of entries) {
            if (entry.name.startsWith('_') || entry.name.startsWith('.')) continue;
            
            const fullPath = path.join(dirPath, entry.name);
            
            if (entry.isDirectory()) {
              // Skip if it's the root directory
              if (fullPath === rootDir) continue;
              
              // Check if breadcrumb file exists for this directory
              const breadcrumbFile = path.join(dirPath, `${entry.name}.mdx`);
              try {
                await fs.access(breadcrumbFile);
              } catch {
                const relativePath = path.relative(rootDir, dirPath);
                errors.push(`Missing breadcrumb file for directory: ${relativePath}/${entry.name}`);
              }
              
              // Recursively check subdirectories
              await checkDirectory(fullPath);
            }
          }
        }

        async function main() {
          try {
            await checkDirectory(rootDir);
            
            if (errors.length > 0) {
              console.error('Breadcrumb check failed:');
              errors.forEach(error => console.error(`- ${error}`));
              process.exit(1);
            } else {
              console.log('All directories have breadcrumb files.');
            }
          } catch (error) {
            console.error('Error checking breadcrumbs:', error);
            process.exit(1);
          }
        }

        main();
        EOL

    - name: Run breadcrumb check
      run: pnpm ts-node utils/check-breadcrumbs.ts

```